### PR TITLE
Swap net6 in-proc hidden state, update SDK version and templates

### LINKED ISSUE #566: Swap the hidden tags between the default and in-proc releases for .NET 6 on the in-process model
The `-inprocess` release will have a copy of the .NET 6 in-process entry when https://github.com/Azure/azure-functions-tooling-feed/issues/563 is resolved. This will need to be swapped over once the custom host version of the core tools has been validated through the feed (#565).

This should be done at earliest alongside release of the SDK which would use this entry (#567). It may come later, but the two items probably should be done at the same time.

### LINKED ISSUE #567: Entry for .NET 6 in-proc should reference SDK and templates versions necessary to use it
Although we have added the entry in https://github.com/Azure/azure-functions-tooling-feed/issues/563, it cannot be used on a default path.

When https://github.com/Azure/azure-functions-vs-build-sdk/issues/657 completes and is released, we need to update the `sdk.version` property of the net6 runtime in the `-inprocess` release. This is expected to be "4.5.0".

At the same time, we should update the templates (across the board). This also requires https://github.com/Azure/azure-functions-templates/issues/1568 to have been completed and released.

### PR DESCRIPTION
**Pull request by mattchenderson**
Resolves #566
Resolves #567

Draft PR - this is to come after #570 and once the new SDK is in place, and the corresponding templates published. Templates PR here: https://github.com/Azure/azure-functions-templates/pull/1567

This will of course need to be rebased atop #570 and any other releases that come through before this is ready.

Current diff gist: https://gist.github.com/mattchenderson/c8fbdefc974f7f0acf06cb7d21af4030/revisions

### CODE REVIEW

**Comment by mattchenderson** [comment]
Rebased against the commit from #570. The gist has also been updated. The templates remain placeholder values which will need to be updated, yet.

**Comment by mattchenderson** [comment]
Updated over latest version. This is still missing the templates at present.

**Comment by mattchenderson** [comment]
This PR now includes an update to include .NET 9 Windows support

**Comment by mattchenderson** [comment]
The PR now includes the expected template version, though this is not yet published. This PR will be marked ready for review once the templates are published.

**Review by fabiocav — APPROVED** [review]
:shipit:

**Pull request merged**
