### PR TITLE
Updating Visual Studio Feed to reflect the .NET support

### LINKED ISSUE #348: [Visual Studio Feed] Update Visual Studio Feed to reflect the .NET support on VS
image

To make string update for these strings:
* LTS -> Long term support. Add it to 6.0

* 3 -> 3.1

* 5 -> 5.0

* 6 -> 6.0

### PR DESCRIPTION
**Pull request by soninaren**
resolves #348

### CODE REVIEW

**Comment by soninaren** [comment]
cc: @vijayrkn , @stefanushinardi

**Comment by vijayrkn** [comment]
+ @phenning 

@soninaren - What are the updated strings? We want to make sure VS honors the new strings.

**Comment by soninaren** [comment]
> * @phenning
> 
> @soninaren - What are the updated strings? We want to make sure VS honors the new strings.

Strings are listed here: https://github.com/Azure/azure-functions-tooling-feed/issues/348#issue-1233280155

image

To make string update for these strings:
* LTS -> Long term support. Add it to 6.0

* 3 -> 3.1

* 5 -> 5.0

* 6 -> 6.0

**Review by phenning — CHANGES_REQUESTED** [review]

**Pull request merged**
