### PR TITLE
Fix netFrameworkVersion for dotnet-isolated 5 apps

### PR DESCRIPTION
**Pull request by pragnagopa**
cc @safihamid

### CODE REVIEW

**Comment by phil-allen-msft** [comment]
Please create a new 'release' for functions-tag-v3 to point to, and update within that.  Otherwise, VS Win for sure won't see the updated values as 'new' and therefore will use the existing serialized settings ("v5" for netFrameworkVersion)

**Review by fabiocav — CHANGES_REQUESTED** [review]
We can only make changes to new releases, we can't update properties on previous releases on the feed. We need to introduce a new version with the updated property instead of updating the existing ones.

**Comment by pragnagopa** [comment]
@soninaren / @fabiocav - Please feel free to close this PR or re-purpose to address the comments. Thanks!

**Comment by fabiocav** [comment]
Thank you! @soninaren will follow up with an update.

**Pull request closed without merging**
